[package]
name = "vrsh"
version = "0.1.0"
authors = ["Vidar Magnusson <git@vidarmagnusson.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rustyline = "8.0.0"
rustyline-derive = "0.4.0"